# Netlify 배포 설정 파일
[build]
  # 빌드 커맨드
  command = "npm run build"
  # 빌드 결과물이 생성되는 디렉토리
  publish = ".next/standalone"
  # Node.js 버전 설정
  [build.environment]
    NODE_VERSION = "20"

# Next.js Essential 플러그인 사용
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
